#!/usr/bin/env python3

import gzip
import shutil

import os
import argparse
import progress.bar
import glob
import gpxpy
import gpxpy.gpx
import folium
import subprocess


def unzip(activities):
    """
    unzips all files in activities folder automatically
    """
    gzipfiles = glob.glob(activities + "/*.gz")
    bar = progress.bar.IncrementalBar('- Unpacking gzip files...', suffix='%(remaining)s/%(max)s - %(percent).1f%% - %(eta)ds', max=len(gzipfiles))
    for f in gzipfiles:
        with gzip.open(f,'rb') as f_in:
            with open(f.replace('.gz', ''), 'wb') as f_out:
                shutil.copyfileobj(f_in,f_out)
                os.remove(f)
                bar.next()
    bar.finish()


def fit2gpx(activities):
    """
    Converts .fit files in activites folder to .gpx
    """

    if shutil.which('gpsbabel') is None:
        print("Warning: gpsbabel not found, not trying to convert any .fit file")
        return False

    fitfiles = glob.glob(activities + "/*.fit")
    bar = progress.bar.IncrementalBar('- Converting .fit files to .gpx...', suffix='%(remaining)s/%(max)s - %(percent).1f%% - %(eta)ds', max=len(fitfiles))
    for f in fitfiles:
        # gpsbabel -i garmin_fit -f foo.fit -o gpx -F foo.gpx
        subprocess.run(["gpsbabel", "-i", "garmin_fit", "-f", f,  "-o", "gpx", "-F", f.replace('.gz', '')])
        os.remove(f)
        bar.next()
    bar.finish()
    return True

def lcount(keyword, fname, rate):
    with open(fname, 'r') as fin:
        return int(sum([1 for line in fin if keyword in line])/rate)

def simplifygpx(activities, rate=3):
    gpxfiles = glob.glob(activities + "/*.gpx")
    bar = progress.bar.IncrementalBar('- Simplifying gpx files by %s' % rate , suffix='%(remaining)s/%(max)s - %(percent).1f%% - %(eta)ds', max=len(gpxfiles))
    for f in gpxfiles:
        # gpsbabel -rt -i gpx -f 4149187130.gpx -x simplify,count=50 -o gpx -F SIMPLIFIED-4149187130.gpx
        count = lcount("trkpt", f, rate)
        subprocess.run(["gpsbabel", "-rt", "-i", "gpx", "-f", f, "-x", "simplify,count=%s" % count, "-o", "gpx", "-F", f.replace('.gpx', '-mini.gpx')])
        os.remove(f)
        bar.next()
    bar.finish()

def draw_file(osm_map, year, gpxfile):
    """
    Checks if gpx track is in time range (year or None)
    Iterates over all tracks, segments and points and adds
    points to maps object.
    :osm_map: map object
    :year: int or None
    :gpxfile: str
    returns: boolean
    """
    points = []
    xfile = open(gpxfile, 'r')
    gpx = gpxpy.parse(xfile)

    # check if file is from this year
    try:
        if gpx.tracks[0].segments[0].points[0].time.year != year and year is not None:
            return False
    except IndexError:
        print("Ignoring file {}. Problem finding tracks, segments or time XML element in the file".format(gpxfile))
        return False

    # loop over tracks
    for track in gpx.tracks:
        for segment in track.segments:
            for point in segment.points:
                points.append(tuple([point.latitude, point.longitude]))

    xfile.close()

    # add line to map
    folium.PolyLine(points, color="red", weight=2.5, opacity=0.5).add_to(osm_map)
    return True


def draw_map(osm_map, files, year):
    """
    Iterates over all files in list and hand over to
    draw track of file to map
    :osm_map: map object
    :files: list of files
    :year: int or None
    :returns: boolean
    """

    bar = progress.bar.IncrementalBar('- Placing dots on a map for %s...' % year, suffix='%(remaining)s/%(max)s - %(percent).1f%% - %(eta)ds', max=len(files))
    for gpxfile in files:
        draw_file(osm_map, year, gpxfile)
        bar.next()
    bar.finish()

    return True

def plot(years, activities):
    """
    Loops over years and draws map
    :years: list
    :returns: boolean
    """

    print("[+] Plotting")
    for year in years:
        osm_map = folium.Map(zoom_start=14)
        draw_map(osm_map, files=glob.glob(activities + "/*.gpx"), year=int(year))
        osm_map.save("./index.{}.html".format(year))
        print("- Wrote {} to ./index.{}.html".format(year, year))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Strava Activites Export Map Builder')
    parser.add_argument('--activities', '-f', type=str)
    parser.add_argument('--years', '-y', action='append', type=str, default=None)
    args = parser.parse_args()
    print("[+] Preparing exported files")
    unzip(args.activities)
    fit2gpx(args.activities)
    #simplifygpx(args.activities)
    plot(args.years, args.activities)
