#!/usr/bin/env python3

import glob
import gpxpy
import gpxpy.gpx
import folium

# gpxfiles = [ 'test.gpx', 'test2.gpx' ]
gpxfiles = glob.glob('./activities/*.gpx')

# Load map centred on average coordinates
my_map = folium.Map(zoom_start=14)

for gpxfile in gpxfiles:
    points = []

    xfile = open(gpxfile, 'r')

    gpx = gpxpy.parse(xfile)
    for track in gpx.tracks:
        for segment in track.segments:
            for point in segment.points:
                points.append(tuple([point.latitude, point.longitude]))

    xfile.close()

    ave_lat = sum(p[0] for p in points)/len(points)
    ave_lon = sum(p[1] for p in points)/len(points)

    folium.PolyLine(points, color="red", weight=2.5, opacity=0.5).add_to(my_map)

# Save map
my_map.save("./index.html")
